### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by ghost** [tableless/iniciantes#123]

**Comment by laurianops** [comment]
muita informação desencontrada mesmo .

**Comment by Sphinxs** [comment]
Três anos depois. Utilizem cheatsheets. Tu consegue ler diversas em um dia e verificar os padrões da tecnologia em questão de forma rápida ( :

**Comment by laurianops** [comment]
abandonaram esse projeto aqui ? só vi mensagens antigas rs

**Comment by Sphinxs** [comment]
Sim, ano passado houve apenas 2 commites e no ano anterior 1 ou 2 se não me engano...

**Comment by laurianops** [comment]
é uma pena @Sphinxs, nessa semana eu vou tentar contribuir ..
