### ISSUE TITLE
Remover/alterar o branch master

### ISSUE THREAD

**Issue by dgmike** [tableless/iniciantes#24]
Ao entrar no projeto existem inúmeros arquivos que não deveriam existir, isto pode deixar os novatos um pouco confusos. Talvez, se o branch master contivesse apenas um arquivo README com instruções do que fazer (para fazer melhorias através de _forks_) e o link para o projeto final: http://tableless.github.io/iniciantes/

Daí manteria apenas o branch `gh-pages`

Outra solução seria remover o branch master, mas voltaria a ter vários arquivos do mesmo.

**Comment by diegoeis** [comment]
O GitHub Pages não faz build do site no Master, né, apenas do branch gh-pages, correto?

Se não faz esse build pelo master mesmo, acho que vale a pena matar o master, deixar apenas o gh-pages e fazer um ignore na pasta _site.

What you think?

**Comment by dgmike** [comment]
ignore na pasta _site? não entendi.

Mesmo assim, acho que vale a pena matar o master e, se possível reduzir a quantidade de arquivos do root. Por exemplo, colocar o `{img, js, css}` dentro de uma pasta mais genérica. `assets` talvez (conforme o padrão do ruby).

Não conheço muito o JEKYLL, mas isso deve dar uma limpada legal.

**Comment by diegoeis** [comment]
A página _site é build estático do projeto. Ele não precisa ser commitado como está sendo feito agora.

Na verdade as pastas com os textos do manual, tipo js, css, html e obasico podem estar dentro de uma pasta manual... Isso já diminuiria muito e não daria conflito com as pastas de assets (js, css).

**Comment by dgmike** [comment]
Great! :+1:

**Comment by diegoeis** [comment]
Acabei de apagar o branch MASTER. Agora o que vale é o gh-pages.
Também movi os arquivos do manual e assets para suas respectivas pastas.

Me matem caso der merda em algum lugar. :-(
