### ISSUE TITLE
Endereço no Tableless sem formatação

### ISSUE THREAD

**Issue by dgmike** [tableless/iniciantes#25]
O link encontrado na descrição do projeto envia para o site do tableless, que não está formatado conforme o projeto deveria ser.

![selection_004](https://f.cloud.github.com/assets/94767/797459/45229dee-ed49-11e2-9ab7-5eb79394f33c.png)

**Comment by diegoeis** [comment]
Já fiz um redirect no Tableless. Agora o endereço principal do projeto vai ser aqui no GitHub.
