### ISSUE TITLE
Padronização da forma de criação dos textos

### ISSUE THREAD

**Issue by wmartins** [tableless/iniciantes#30]
Eu tive um pouco de dúvidas enquanto eu estava criando os textos, quis colocar alguns subtítulos, alguns códigos (tags principalmente) e não tinha certeza de como marcá-los, então fiz o mais 'simples' e coloquei algumas tags como &lt;b&gt;, &lt;i&gt; e &lt;code&gt;.

Acho que seria legal para quem quer contribuír que seja realizado um pequeno guia de contribuição, abordando esses principais casos. Isso facilitaria bastante na hora de criar e editar os textos (e também facilitaria muito se quisessemos mudar o estilo das páginas).

**Comment by diegoeis** [comment]
Funciona assim:
tag &lt;code&gt; pode ser inserida dentro de parágrafos para indicar palavras relacionadas a código. Ele deixa a palavra em negrito para destacar melhor.

Para colocar sintaxe de código, vamos usar agora o padrão do Google Prettify. Já está instalado e funcionando. Um exemplo pode ser visto no texto de Estrutura Básica do HTML.
