### ISSUE TITLE
Guia para trabalhar com Jekyll.

### ISSUE THREAD

**Issue by wmartins** [tableless/iniciantes#31]
Acho que seria legal criar um pequeno guia de instalação e utilização do Jekyll (visando contribuír com o projeto, não é necessário abordar tudo o que o Jekyll disponibiliza).
Isso poderia fazer com que um pessoal mais novo em programação (que possivelmente nunca mexeu com ruby) pudesse contribuír com mais facilidade, sem ter que garimpar tutoriais de instalação na web.

O que acham?

**Comment by thulioph** [comment]
Nesse momento to procurando material na net pra me ajudar a mecher no Jekyll já é mais um aprendizado rsrs. Não vou mentir que seria de bom tamanho esse guia proposto, mas vamo que vamo!

**Comment by wmartins** [comment]
@thulioph de repente eu vou criar uma página na wiki pra explicar isso, o que acham? @diegoeis @tableless @wbruno

**Comment by vitornp** [comment]
Como podem vê eu criei um Jekyll no próprio README.md, pois eu achei fácil e prático a utilização. O que você acha @wmartins

**Comment by wmartins** [comment]
Boa @vitornp , achei legal! Vamos ver o que o pessoal acha, ficou bem simples e bem direto!

**Comment by marcelomatz** [comment]
E aí @wmartins e @vitornp eu achei bem legal esse manual. É a primeira vez que eu to usando Jekyll. Tanto que no Pull Request que eu dei, eu usei tags html para estruturar o documento. Agora vou procurar um plugin para o Sublime Text :)

**Comment by vitornp** [comment]
Valeu @wmartins @barramatz!!!
Caso vc achar algum plugin legal indica ai para galera

**Comment by diegoeis** [comment]
@thulioph viu já este post?
http://tableless.com.br/jekyll-servindo-sites-estaticos/

**Comment by diegoeis** [comment]
Se vermos que precisa de algo mais didático, fazemos.
Por hora essa explicação do @vitornp está ótimo.
