### ISSUE TITLE
Mudança de fonte.

### ISSUE THREAD

**Issue by oswaldoacauan** [tableless/iniciantes#35]
Utilizando Chrome (28.0.1500.72) e Windows 7 a fonte atual (Lato) está deixando a leitura muito cansativa, é necessário esforço para leitura dos textos.

**Comment by diegoeis** [comment]
Manda um printscreen para gente ver.

**Comment by oswaldoacauan** [comment]
![print](https://f.cloud.github.com/assets/1268518/902114/c17a452e-fb8e-11e2-81fa-49ae666ffd47.png)

Chrome vs Firefox

**Comment by diegoeis** [comment]
Será que não resolve colocando o font-smoothing?
Faz um teste aí no inspect mesmo. Testei aqui no Chrome para Mac e está ok!
