### ISSUE TITLE
Texto: O que são Objetos?

### ISSUE THREAD

**Issue by HenriqueSilverio** [tableless/iniciantes#49]
Estou trabalhando na escrita deste "capítulo".

**Comment by diegoeis** [comment]
Coisa linda!
Valeu!

Abraço,
Diego Eis

http://about.me/diegoeis/
http://tableless.com.br/
http://tableless.com.br/aula-particular

2013/9/14 Henrique Silvério notifications@github.com

**Comment by marcelomatz** [comment]
Cara, teve um Copy and Paste bem maluco aí, heim hehehe

**Comment by wbruno** [comment]
http://tableless.github.io/iniciantes/manual/js/objetos.html
