### ISSUE TITLE
Commits em inglês ou português?

### ISSUE THREAD

**Issue by diessica** [tableless/iniciantes#63]
Os projetos geralmente possuem um guia para contribuição avisando, também, em qual idioma os commits devem estar.
Como esse é um projeto muito focado na colaboração da comunidade, é importante que isso fique mais claro.

Afinal, os commits devem ser em inglês (mais universal) ou português (mais restrito ao Brasil)?

**Comment by diegogurgel** [comment]
Sugiro em português mesmo.

**Comment by diegoeis** [comment]
Aqui temos um problema interessante para gente pensar: como é um projeto focado para iniciantes brasileiros, seria interessante que os commits fossem em português para que os próprios iniciantes pudessem entender, futuramente, como funciona um projeto como esse.

Fechado português então?

**Comment by dgmike** [comment]
Português Brasil :+1:

**Comment by cirocosta** [comment]
pt-br :+1:

**Comment by dgmike** [comment]
Michael Granados sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/2d7b0164-0888-4267-906c-fd239f76f953

## 

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=bd8a251fcc6b41eb905fa37e342963a6&uid=0&c=IuVwbCB3dgF1eqLh%2FhwrcAEp0QOCeUenl7Yzkh9KFaRRPMSLg%2F6Rw099grpT%2Fc2FkTNwbnNyBL4Fs7o1brFFOqDFo%2BFu0sqTqaYndyUe2DTuMAu7W1VWPw%3D%3D&nid=9+26

Need help?
https://support.twitter.com

**Comment by diegoeis** [comment]
Fechou então pt-br...
Closing.
