### ISSUE TITLE
Texto: o que é jQuery?

### ISSUE THREAD

**Issue by diegoeis** [tableless/iniciantes#73]
http://tableless.github.io/iniciantes/manual/js/o-que-jquery.html

**Comment by maracaipe** [comment]
Escrevendo...

**Comment by raphaelfabeni** [comment]
Fala @maracaipe beleza?
Acabei deixando passar, não vi que você estava escrevendo e comecei uma versão inicial do texto.
Vou enviar um pull request, mas, como você já havia iniciado, fique a vontade para editar do jeito que achar melhor.
Valeu!

**Comment by maracaipe** [comment]
Pode enviar man, acabei ficando sem tempo de finalizar o texto, obrigado!

Enviado via iPhone

**Comment by raphaelfabeni** [comment]
Valeu man!

**Comment by euconectei** [comment]
Merged
